apiVersion: v1
kind: PersistentVolume
metadata:
  name: idisclose-postgres-data-persisent-volume
  labels:
    type: local
spec:
  claimRef:
    namespace: default
    name: idisclose-postgres-data-persisent-volume-claim
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  # change if not on microk8s
  hostPath:
    path: "/home/mario/Documents/progetti/phoenix/idisclose/idisclose-postgres-data"
