apiVersion: v1
kind: Service
metadata:
  name: idisclose-db-service
spec:
  type: ClusterIP
  selector:
    app: idisclose-db
  ports:
    - name: "postgres"
      protocol: TCP
      port: 5432
      targetPort: 5432

