apiVersion: v1
kind: Secret
metadata:
  name: dev-secret
type: Opaque
data:
  db_user: cG9zdGdyZXM=
  db_password: cG9zdGdyZXM=
  secret-cookie: cUhPQlVLbkVqRkI1clZ5VndGdGQ2ZWNYMng4UGN6UksvTVZGMWZ2NjBOZ0x5dG5sbzdhMVhiZDBjQWl5amkycQo=
