apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-list-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-list-role-binding
subjects:
  - kind: ServiceAccount
    name: idisclose-service-account
    namespace: default
roleRef:
  kind: Role
  name: pod-list-role
  apiGroup: rbac.authorization.k8s.io

