apiVersion: v1
kind: Service
metadata:
  name: idisclose-web-service
spec:
  type: NodePort
  selector:
    app: idisclose-web
  ports:
    - name: "http"
      protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 30000
    #- name: "https"
      #protocol: TCP
      #port: 4001
      #targetPort: 4001
      #nodePort: 30001

