@startsalt
title Login page
{+
{/ iDisclose }
{+
  "https://idisclose.com/login                                                                                                                                  "
}
{* Home | Sections | Templates | Documents | Profile }
{
  .
  .
  .
  .
  .
  .
  .
  .
}
{
  Login    | "email    "
  Password | "****     "
  [  LOGIN  ]
}
{
  .
  .
  .
  .
  .
  .
  .
  .
}
}
@endsalt

