@startsalt
title Section page
{+
{/ iDisclose }
{+
  "https://idisclose.com/sections                                                                                                                               "
}
{* Home | Templates | Documents | Profile }
{
  Login    | "email    "
  Password | "****     "
  [  LOGIN  ]
}

}
@endsalt

