name: Push to Docker on merge

on:
  pull_request:
    types:
      - closed

jobs:
  build_and_push_image: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get commit hash
        id: commit_hash
        run: echo "GITHUB_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Get current timestamp
        id: timestamp
        run: echo "GITHUB_TIMESTAMP=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Build image 
        run: docker build -t marioanticoli/idisclose:${{ env.GITHUB_TIMESTAMP }}-${{ env.GITHUB_HASH }} -f Dockerfile .

      - name: Push Docker Image to Docker Hub
        run: docker push marioanticoli/idisclose:${{ env.GITHUB_TIMESTAMP }}-${{ env.GITHUB_HASH }}

