name: Phoenix App Checks

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: idisclose_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Restore Cache
        id: deps-cache
        uses: actions/cache@v2
        with:
          path: |
            mix.lock
            deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}

      - name: Build Phoenix App
        run: docker build -t idisclose:test -f ./docker/Dockerfile.test .

      - name: Save Cache
        id: deps-cache
        uses: actions/cache@v2
        with:
          path: |
            mix.lock
            deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}

      - name: Run sobelow
        run: docker run --rm idisclose:test mix sobelow

      - name: Run dialyzer
        run: docker run --rm idisclose:test mix dialyzer --format short

      - name: Run credo 
        run: docker run --rm idisclose:test mix credo

      - name: Run Phoenix App Tests
        run: docker run --rm --add-host=host.docker.internal:host-gateway -e DB_HOSTNAME=host.docker.internal idisclose:test mix test

  #build: 
    #needs: test 
    #runs-on: ubuntu-latest

    #steps:
      #- name: Checkout Repository
        #uses: actions/checkout@v2

      #- name: Build image 
        #run: docker build -t marioanticoli/idisclose:latest -f ./docker/Dockerfile .

  #push_image:
    #needs: build 
    #runs-on: ubuntu-latest

    #steps:
      #- name: Log in to Docker Hub
        #run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      #- name: Push Docker Image to Docker Hub
        #run: docker push marioanticoli/idisclose:latest 

